{
 "title": "Traefik",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open Connections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traefik_open_connections", "legendFormat": "{{entrypoint}}" }
   ]
  },
  { "title": "Service Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Service request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "traefik_service_requests_total",
     "legendFormat": "{{service}} - {{method}} - {{code}} "
    }
   ]
  },
  {
   "title": "Grafana Service, GET Method, 200 Response Request Duration histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_service_request_duration_seconds_bucket{service=\"grafana@docker\", method=\"GET\", code=\"200\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Entrypoints Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Rate of HTTP Requests for Web EntryPoint",
   "type": "timeseries",
   "description": "calculates the average number of HTTP requests coming to a given Entrypoint in a given time interval f ex. if there were 0.133 queries per second for 5 minutes (300 seconds), that gives a total of about 40 queries during those 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=\"web\"}[$__rate_interval])",
     "legendFormat": "{{code}} - {{method}}"
    }
   ]
  },
  {
   "title": "Rate of HTTP Requests for WebSecure EntryPoint",
   "type": "timeseries",
   "description": "calculates the average number of HTTP requests coming to a given Entrypoint in a given time interval f ex. if there were 0.133 queries per second for 5 minutes (300 seconds), that gives a total of about 40 queries during those 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=\"websecure\"}[$__rate_interval])",
     "legendFormat": "{{code}} - {{method}}"
    }
   ]
  },
  {
   "title": "Responses Bytes (Total) - MB for Web EntryPoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "(traefik_entrypoint_responses_bytes_total{entrypoint=\"web\"})/1048576",
     "legendFormat": "{{code}} - {{method}}"
    }
   ]
  },
  {
   "title": "Responses  Bytes (Total) - MB for WebSecure EntryPoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "(traefik_entrypoint_responses_bytes_total{entrypoint=\"websecure\"})/1048576",
     "legendFormat": "{{code}} - {{method}}"
    }
   ]
  },
  {
   "title": "Requests Bytes (Total) - MB for Web EntryPoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "(traefik_entrypoint_requests_bytes_total{entrypoint=\"web\"})/1048576",
     "legendFormat": "{{code}} - {{method}}"
    }
   ]
  },
  {
   "title": "Requests Bytes (Total) - MB for WebSecure EntryPoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "(traefik_entrypoint_requests_bytes_total{entrypoint=\"websecure\"})/1048576",
     "legendFormat": "{{code}} - {{method}}"
    }
   ]
  }
 ]
}